apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  ports:
  - port: 3306
    protocol: TCP
  type: ClusterIP
  selector:
    app: guestbook
    tier: frontend
